#!/bin/bash

# from development to production
# development server

ot-git checkout test
ot-git pull
ot-git checkout master
ot-git pull
ot-git merge test
ot-git push
ot-git checkout development
ot-git merge master

# production server

ssh -p 106 toxcreate.org "sudo `which gem` update opentox-ruby-api-wrapper --no-rdoc --no-ri"
ssh -p 106 toxcreate.org "/home/ch/bin/ot-git pull"
ssh -p 106 toxcreate.org "/home/ch/bin/nginx-stop"
ssh -p 106 toxcreate.org "/home/ch/bin/nginx-start"
